source :rubygems

# App Stack
gem "sinatra", "~> 1.3"

<% unless @no_database -%>
# Database Stack
<% unless @database == 'mongo' -%>
gem "sequel"
<% end -%>
<% if @database == "sqlite" -%>
gem "sqlite3"
<% elsif @database == "postgres" -%>
gem "pg"
<% elsif @database == "mysql" -%>
gem "mysql2"
<% elsif @database == "mongo" -%>
gem "bson_ext", "~> 1.6"
gem "mongodb_model", "~> 2.1"
<% end -%>
<% end -%>

<% if @redis -%>
# Redis
gem "hiredis", "~> 0.4"
gem "redis", "~> 3.0", :require => ["redis/connection/hiredis", "redis"]
gem "fakeredis", "~> 0.4"

<% end -%>
group :development do
  gem "rake", "~> 0.9"
  gem "minitest", "~> 4.2"
  gem "rack-test", "~> 0.6"
<% if @capistrano -%>
  gem "capistrano", "~> 2.13"
  gem "capistrano-ext", "~> 1.2"
<% if @rvm_gemset -%>
  gem "rvm-capistrano", "~> 1.2"
<% end -%>
<% end -%>
end
