%w{ rubygems bundler find rake/testtask}.each { |lib| require lib }

task :default => :spec

Rake::TestTask.new(:spec) do |t|
  t.test_files = FileList['spec/*_spec.rb']
  t.ruby_opts = ['-rubygems'] if defined? Gem
  t.ruby_opts << '-I.'
end

namespace :db do
  desc "Run all migrations in db/migrate"
  task :migrate => :connect do
    Sequel.extension(:migration)
    Sequel::Migrator.apply(DB, "db/migrate")
  end

  task :connect => :environment do
    require "./config/initializers/database"
  end
end

task :environment, [:env] do |cmd, args|
  Bundler.require
  ENV['RACK_ENV'] = args[:env] || "development"
  %w{ ./config/initializers ./lib }.each do
    Find.find(lib) { |f| require f unless f.match(/\/\..+$/) || File.directory?(f) }
  end
end


