%w{ rubygems bundler find rake/testtask}.each { |lib| require lib }

task :default => :spec

Rake::TestTask.new(:spec) do |t|
  t.test_files = FileList['spec/*_spec.rb']
  t.ruby_opts = ['-rubygems'] if defined? Gem
end

task :kicker do
  exec 'kicker -r ruby -e "clear && bundle exec rake" spec lib'
end

task :sass do
  exec 'sass --watch --scss --style compressed sass/main.scss:public/stylesheets/main.css'
end

<% unless @no_database -%>
namespace :db do
  desc "Run all migrations in db/migrate"
  task :migrate => :connect do
    Sequel.extension(:migration)
    Sequel::Migrator.apply(DB, "db/migrate")
  end

  task :connect => :environment do
    require "./config/initializers/database"
  end
end
<%end%>
